<template>
  <section class="section">
    <div class="container">
      <div class="columns">
        <div class="column is-8-desktop is-offset-2-desktop">
          <h1 class="title is-2">Privacy Policy</h1>

          <p>WriteFlow is committed to protecting your privacy. We have prepared this Privacy Policy to describe to you our practices regarding the Personal Data (as defined below) we collect from users of our website located at getwriteflow.com and in connection with our and related products and services (the "Services").</p>

          <p>1. USER CONSENT. By submitting Personal Data through our website or Services, you agree to the terms of this Privacy Policy and you expressly consent to the processing of your Personal Data in accordance with this Privacy Policy.</p>

          <p>2. A NOTE ABOUT CHILDREN. We do not intentionally gather Personal Data about visitors who are under the age of 13.</p>

          <p>3. TYPES OF DATA WE COLLECT. We collect Personal Data and Anonymous Data from you when you visit our site, when you send us information or communications, when you use our Services, and when you register for white papers, web seminars, and other events hosted by us. "Personal Data" means data that allows someone to identify or contact you, including, for example, your name, address, telephone number, e-mail address, as well as any other non-public information about you that is associated with or linked to any of the foregoing data. "Anonymous Data" means data that is not associated with or linked to your Personal Data; Anonymous Data does not permit the identification of individual persons.</p>

          <p>3.1 Personal Data You Provide to Us. We collect Personal Data from you, which may include your first and last name, gender, e-mail and mailing addresses, professional title, company name, and password when you use the Services, create an account, or sign-up for our newsletter or other marketing material. When you order Services on our website, we will collect all information necessary to complete the transaction, including your name, credit card information, billing information and shipping information. We also retain information on your behalf, such as files and messages that you store using your account. If you provide us feedback or contact us via e-mail or submit a response to an employment opportunity posted on our website, we will collect your name and e-mail address, as well as any other content included in the e-mail, in order to send you a reply, and any information that you submit to us, such as a resume. When you participate in one of our surveys, we may collect additional profile information. When you post messages on the message boards of our website, the information contained in your posting will be stored on our servers and other users will be able to see it. We also collect other types of Personal Data that you provide to us voluntarily, such as operating system and version, Product version numbers, and other requested information if you contact us via e-mail regarding support for the Services. We may also collect Personal Data, such as demographic information, from you via the Services or at other points in our website that state that Personal Data is being collected.</p>

          <p>3.2 Personal Data Collected via Technology. To make our website and Services more useful to you, our servers (which may be hosted by a third party service provider) collect Personal Data from you, including browser type, operating system, Internet Protocol (IP) address (a number that is automatically assigned to your computer when you use the Internet, which may vary from session to session), domain name, and/or a date/time stamp for your visit. We may also use Cookies (as defined below) and navigational data like Uniform Resource Locators (URL) to gather information regarding the date and time of your visit and the solutions and information for which you searched and which you viewed. Like most technology companies, we automatically gather this Personal Data and store it in log files each time you visit our website or access your account on our network. "Cookies" are small pieces of information that a website sends to your computer's hard drive while you are viewing a web site. We may use both session Cookies (which expire once you close your web browser) and persistent Cookies (which stay on your computer until you delete them) to provide you with a more personal and interactive experience on our website. Persistent Cookies can be removed by following Internet browser help file directions. If you choose to disable Cookies, some areas of our website may not work properly.</p>

          <p>3.3 Personal Data That We Collect from You About Others. If you decide to create an account for and invite a third party to join our network, we will collect your and the third party's names and e-mail addresses in order to send an e-mail and follow up with the third party. You or the third party may contact us at support@getwriteflow.com to request the removal of this information from our database.</p>

          <p>4. USE OF YOUR DATA</p>

          <p>4.1 General Use. In general, Personal Data you submit to us is used either to respond to requests that you make, or to aid us in serving you better. We use your Personal Data in the following ways: to facilitate the creation of and secure your account on our network; identify you as a user in our system; provide improved administration of our website and Services; improve the quality of experience when you interact with our website and Services; send you a welcome e-mail to verify ownership of the e-mail address provided when your account was created; send you administrative e-mail notifications, such as security or support and maintenance advisories; respond to your inquiries related to employment opportunities or other requests; to send promotional communications; to provide you with hardcopy or electronic newsletters or surveys; to send upgrades and offers related to our Services; and for other our, or our Third Party Company (as defined below), marketing purposes should you opt-in to receive such communications by following the instructions we provide; to make telephone calls to you, from time to time, as a part of secondary fraud protection or to solicit your feedback.</p>

          <p>4.2 Creation of Anonymous Data. We may create Anonymous Data records from Personal Data by excluding information (such as your name) that makes the data personally identifiable to you. We use this Anonymous Data to analyze request and usage patterns so that we may enhance the content of our Services and improve site navigation. We reserve the right to use and disclose Anonymous Data to Third Party Companies in our discretion.</p>

          <p>4.3 Feedback. If you provide feedback on any of our Services or our website, we may use such feedback for any purpose, provided we will not associate such feedback with your Personal Data. We will collect any information contained in such communication and will treat the Personal Data in such communication in accordance with this Privacy Policy.</p>

          <p>5. DISCLOSURE OF YOUR PERSONAL DATA</p>

          <p>5.1 Affiliates. Although we currently do not have a parent company, any subsidiaries, joint ventures, or other companies under a common control (collectively, "Affiliates"), we may in the future. We may share some or all of your Personal Data with these Affiliates, in which case we will require our Affiliates to honor this Privacy Policy. If another company acquires us or our assets, that company will possess the Personal Data collected by it and us and will assume the rights and obligations regarding your Personal Data as described in this Privacy Policy.</p>

          <p>5.2 Other Disclosures. Regardless of any choices you make regarding your Personal Data (as described below), we may disclose Personal Data if we believe in good faith that such disclosure is necessary to (a) comply with relevant laws or to respond to subpoenas or warrants served on us; (b) protect or defend the our rights or property or the rights or property of users of the Services; or (c) protect against fraud and reduce credit risk.</p>

          <p>6. THIRD PARTIES</p>

          <p>6.1 Personal and/or Anonymous Data Collected by Third Parties.</p>

          <p>(a) We may receive Personal and/or Anonymous Data about you from other sources like telephone or fax, or from companies that provide our Services by way of a co-branded or private-labeled website or companies that offer their products and/or services on our website ("Third Party Companies"). Our Third Party Companies may supply us with Personal Data, such as your calendars and address book information, in order to help us establish the account. We may add this information to the information we have already collected from you via our website in order to improve the Services we provide.</p>

          <p>(b) Our provision of a link to any other website or location, such as the Stripe payment processing websites, is for your convenience and does not signify our endorsement of such other website or location or its contents. When you click on such a link, you will leave our site and go to another site. During this process, another entity may collect Personal Data or Anonymous Data from you.</p>

          <p>(c) We have no control over, do not review, and cannot be responsible for, these outside websites or their content. Please be aware that the terms of this Privacy Policy do not apply to these outside websites or content, or to any collection of data after you click on links to such outside websites. You may determine whether or not we are responsible for the content of a website by reviewing the URL and confirming the ownership of the applicable domain by means of a service such as DNSstuff.com.</p>

          <p>6.2 Disclosure to Third Party Service Providers. Except as otherwise stated in this policy, we do not generally sell, trade, share, or rent the Personal Data collected from our services to other entities. However, we may share your Personal Data with third party service providers to provide you with the Services that we offer you through our website; to conduct quality assurance testing; to facilitate creation of accounts; to provide technical support; or to provide specific services, such as synchronization with other software applications. These third party service providers are required not to use your Personal Data other than to provide the services requested by us. You expressly consent to the sharing of your Personal Data with our contractors and other service providers for the sole purpose of providing services to you.</p>

          <p>6.3 Disclosure to Third Party Companies. We may enter into agreements with Third Party Companies. A Third Party Company may want access to Personal Data that we collect from our customers. As a result, we may disclose your Personal Data to a Third Party Company; however, we will not disclose your Personal Data to Third Party Companies for the Third Party Companies' own direct marketing purposes, unless you have "opted-in" by following the instructions we provide to allow such disclosure. If you have opted-in to receive e-mail communications from a Third Party Company and later wish to discontinue receipt of these e-mails, please contact the Third Party Company directly to update your preferences. The privacy policies of our Third Party Companies may apply to the use and disclosure of your Personal Data that we collect and disclose to such Third Party Companies. Because we do not control the privacy practices of our Third Party Companies, you should read and understand their privacy policies.</p>

          <p>7. YOUR CHOICES REGARDING YOUR PERSONAL DATA</p>

          <p>7.1 Choices. We offer you choices regarding the collection, use, and sharing of your Personal Data. We will periodically send you free newsletters and e-mails that directly promote the use of our site or the purchase of our Services and may contain advertisements for Third Party Companies. When you receive newsletters or promotional communications from us, you may indicate a preference to stop receiving further communications from us and you will have the opportunity to "opt-out" by following the unsubscribe instructions provided in the e-mail you receive or by contacting us directly (please see contact information below). Should you decide to opt-out of receiving future mailings, we may share your e-mail address with third parties to ensure that you do not receive further communications from third parties. Despite your indicated e-mail preferences, we may send you notices of any updates to our Privacy Policy.</p>

          <p>7.2 Changes to Personal Data. You may change any of your Personal Data in your account by sending an e-mail to us at the e-mail address set forth below. You may request deletion of your Personal Data by us, but please note that we may be required (by law or otherwise) to keep this information and not delete it (or to keep this information for a certain time, in which case we will comply with your deletion request only after we have fulfilled such requirements). When we delete any information, it will be deleted from the active database, but may remain in our archives.</p>

          <p>8. SECURITY OF YOUR PERSONAL DATA. We are committed to protecting the security of your Personal Data. We use a variety of industry-standard security technologies and procedures to help protect your Personal Data from unauthorized access, use, or disclosure. We also require you to enter a password to access your account information. Please do not disclose your account password to unauthorized people. Despite these measures, you should know that we cannot fully eliminate security risks associated with Personal Data and mistakes may happen.</p>

          <p>9. CONTACT INFORMATION. We welcome your comments or questions regarding this Privacy Policy. Please contact us at support@getwriteflow.com.</p>

          <p>10. DISPUTE RESOLUTION. If you believe that we have not adhered to this Privacy Policy, please contact us at support@getwriteflow.com. We will do our best to address your concerns. If you feel that your complaint has been addressed incompletely, we invite you to let us know for further investigation. If we are unable to reach a resolution to the dispute, we will settle the dispute exclusively under the rules of the American Arbitration Association.</p>

          <p>11. CHANGES TO THIS PRIVACY POLICY. This Privacy Policy is subject to occasional revision, and if we make any substantial changes in the way we use your Personal Data, we will notify you by sending you an e-mail to the last e-mail address you provided to us or by prominently posting notice of the changes on our website. Any material changes to this Privacy Policy will be effective upon the earlier of thirty (30) calendar days following our dispatch of an e-mail notice to you or thirty (30) calendar days following our posting of notice of the changes on our site. These changes will be effective immediately for new users of our website and Services. Please note that at all times you are responsible for updating your Personal Data to provide us with your most current e-mail address. In the event that the last e-mail address that you have provided us is not valid, or for any reason is not capable of delivering to you the notice described above, our dispatch of the e-mail containing such notice will nonetheless constitute effective notice of the changes described in the notice. In any event, changes to this Privacy Policy may affect our use of Personal Data that you provided us prior to our notification to you of the changes. If you do not wish to permit changes in our use of your Personal Data, you must notify us prior to the effective date of the changes that you wish to deactivate your account with us. Continued use of our website or Services, following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.</p>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
  p, ul {
    margin-bottom: 1.5rem;
  }
</style>
