<template>
  <section class="section">
    <div class="container">
      <div class="columns">
        <div class="column is-8-desktop is-offset-2-desktop">
          <h1 class="title is-2">Terms of Service</h1>

<p>WriteFlow ("we," "us," or "our") is pleased to offer certain web services ("Services") according to the terms and conditions in this Agreement ("Agreement"). By creating an account to use the Services you agree to this Agreement. If you represent an organization, you represent and warrant that you are authorized to agree to this Agreement on behalf or your organization. If you do not agree to this Agreement, do not use the Services.</p>

<p>1. SERVICES</p>
<p>You may access and use our Services in accordance with this Agreement. The Services may include features or services that have separate rules specific to the feature or service. You will comply with all laws, rules, and regulations applicable to the use of the Services and any additional feature or service you use. You may access and use the Services solely for your internal business purposes. You understand and agree that we may change, suspend or discontinue any part of the Services and the Services as a whole. We will notify you of any material change to or discontinuation of the Services by email or via our website.</p>

<p>2. REGISTRATION AND YOUR ACCOUNT</p>
<p>To register to use the Services you must provide an email address and password. Do not disclose your password or other authentication information to any unauthorized persons. You are responsible for all activities that occur under your account, regardless of whether undertaken by you, your employees or a third party (including contractors or agents) and we and our affiliates are not responsible for unauthorized access to your account. You will contact us immediately if you believe an unauthorized third party may be using your account or if your account information is lost or stolen. You will provide complete and accurate information during the registration process and will update it to ensure it remains accurate.</p>

<p>3. YOUR DATA</p>
<p>You are solely responsible for the development, content, operation, maintenance, and use of your data. You will ensure that your data, and your use of it, complies with this Agreement and any applicable law. You are responsible for properly using the Services and taking your own steps to maintain appropriate security, of your data. If you include any data about any individual in your use of our Service, (1) we will hold and store your data on your behalf, and you are the data controller of such data; (2) we will process this data in compliance with your instructions and will not use or process any of this data for any purpose except the performance of our obligations under this Agreement; and (3) you warrant that your instructions to us comply with applicable privacy and data protection laws and that you have all appropriate consents enabling you to use our Service. You represent and warrant that you will not store or process protected health information using the Service. We will use commercially reasonable efforts to prevent the unauthorized disclosure or destruction of your stored information and data. We routinely collect and analyze metadata regarding user files and usage data, excluding any personal data, but including header information, checksum quantities, file size, file type, and archival dates. We use this information to gauge Services levels and application performance, for our own marketing purposes, and, in some instances, for data recovery purposes. We do not make previous historical usage data available to you, and may delete any usage data older than 30 days.</p>

<p>4. PAYMENT AND TAXES</p>
<p>(a) Services Fees. We calculate and bill fees and charges as described on the Service site. If you choose monthly billing by credit card, you authorize a recurring monthly charge to your credit card for the Service based on our current fee schedule for the Service. You will pay us the applicable fees and charges for use of the Services as described on the site using your credit card. All amounts payable for the Services will be made without setoff or deduction, and all amounts paid are non-refundable. We may increase or add new fees and charges for the Service at any time. In the event that we change the pricing for the Service, the fees payable by you may increase or decrease in accordance with any such modification upon the date specified on the Service site.</p>

<p>(b) Taxes. All fees and charges payable by you are exclusive of applicable taxes and duties, including VAT and applicable sales tax. You will provide us any information we reasonably request to determine whether we are obligated to collect VAT from you, including your VAT identification number. If you are legally entitled to an exemption from any sales, use, or similar transaction tax, you are responsible for providing us with legally-sufficient tax exemption certificates for each taxing jurisdiction. We will apply the tax exemption certificates to charges under your account occurring after the date we receive the tax exemption certificates. If any deduction or withholding is required by law, you will notify us and will pay us any additional amounts necessary to ensure that the net amount that we receive, after any deduction and withholding, equals the amount we would have received if no deduction or withholding had been required. Additionally, you will provide us with documentation showing that the withheld and deducted amounts have been paid to the relevant taxing authority.</p>

<p>5. SUSPENSION FOR NON-PAYMENT</p>
<p>Without limiting other available remedies included in this Agreement or otherwise, we may suspend your access to the Services if you are late in payment.</p>

<p>6. TERM; TERMINATION</p>
<p>(a) Term; Termination. The term of this Agreement commences when you create an account and will remain in effect until terminated in accordance with this Agreement. You may terminate this Agreement by terminating your account, and we may terminate this Agreement for any reason by providing you immediate notice. We may also terminate your account and this Agreement, or suspend your account, immediately if (i) we change the way we provide or discontinue the Service; (ii) your account was suspended under Section 5 of this Agreement and you have not remediated the reason for the suspension; or (iii) we determine that: (1) your use of the Services poses a security risk to the Services or any third party; (2) your use of the Services may adversely impact the Services; (3) your use of the Services may subject us, our affiliates, or any third party to liability; (4) your use of the Services may be fraudulent; (5) you are in breach of this Agreement; or (6) you have ceased to operate in the ordinary course, made an assignment for the benefit of creditors or similar disposition of your assets, or become the subject of any bankruptcy, reorganization, liquidation, dissolution or similar proceeding. If we suspend your right to access or use any portion or all of the Services you remain responsible for all fees and charges you have incurred through the date of suspension and you will not be entitled to any credit or refund.</p>

<p>(b) Effect of Termination. Upon termination of this Agreement (i) all your rights under this Agreement immediately terminate and (ii) you remain responsible for all fees and charges you have incurred through the date of termination, including fees and charges for in-process tasks completed after the date of termination. We have no obligation to continue to store your data once you have terminated or after termination of this Agreement.</p>

<p>7. INTELLECTUAL PROPERTY RIGHTS AND OWNERSHIP</p>
<p>(a) Your Data. You represent and warrant to us that: (a) you or your licensors own all right, title, and interest in and to your data; (b) you have all rights in your data necessary to grant the rights contemplated by this Agreement; and (c) none of your data violates this Agreement, any applicable law or any third party’s intellectual property or other right. You consent to our use of your data to provide the Services to you. We may disclose your data to provide the Services to you or to comply with any request of a governmental or regulatory body (including subpoenas or court orders).</p>

<p>(b) Our Service. You may not: (a) modify, alter, tamper with, repair, or otherwise create derivative works of any software included in the Service; (b) reverse engineer, disassemble, or decompile the Services or apply any other process or procedure to derive the source code of any software included in the Service; (c) access or use the Services in a way intended to avoid incurring fees or exceeding usage limits or quotas; (d) resell or sublicense the Service; (e) use the Services in connection with any fork or derivative work of the WriteFlow database; (f) attempt to disable or circumvent any security mechanisms used by the Services; (g) use the Services to perform a malicious activity; or (h) upload or otherwise process any malicious content to or through the Services.</p>

<p>(c) No Other Rights. This Agreement does not transfer any right, title or interest in any intellectual property right to the other, except as expressly set forth in this Agreement. You are not obligated to provide us with any suggestions or other feedback about the Services or otherwise, but if you do, we may use and modify this feedback without any restriction or payment.</p>

<p>8. NO WARRANTY</p>
<p>The Services are provided on an "AS IS" and "AS AVAILABLE" basis and with no representation or warranty of any kind. Except to the extent prohibited by law, we disclaim any implied or statutory warranty, including any implied warranty of merchantability or fitness for a particular purpose, and any warranty arising out of any course of dealing or usage of trade.</p>

<p>9. LIMITATION OF LIABILITY</p>
<p>We and our affiliates and licensors will not be liable to you for any indirect, incidental, special, consequential or exemplary damages (including damages for loss of profits, goodwill, use, or data). We and our affiliates and licensors will not be responsible for any compensation, reimbursement, or direct damages arising in connection with: (a) your inability to use the Service, (b) the cost of procurement of substitute goods or services; (c) any investments, expenditures, or commitments by you in connection with this Agreement or your use of or access to the Service; or (d) any unauthorized access to, alteration of, or the deletion, destruction, damage, loss or failure to store any of your content or other data. Our and our affiliates’ and licensors’ aggregate liability for any permitted direct damages under this agreement will be limited to the amount you actually pay us under this agreement for the Services that gave rise to the claim during the 12 months preceding the claim.</p>

<p>10. INDEMNIFICATION</p>
<p>You will defend, indemnify, and hold harmless us, our affiliates and licensors, and each of their respective employees, officers, directors, and representatives from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising out of or relating to any third party claim concerning: (a) your use of the Services (including any activities under your account and use by your employees and personnel); (b) breach of this Agreement or violation of applicable law by you; or (c) your data or the combination of your data with other applications, content or processes, including any claim involving alleged infringement or misappropriation of third-party rights by your data or by the use, development, design, production, advertising or marketing of your data. If we or our affiliates are obligated to respond to a third party subpoena or other compulsory legal order or process described above, you will also reimburse us for reasonable legal fees, as well as our employees’ and contractors’ time and materials spent responding to the third party subpoena or other compulsory legal order or process at our then-current hourly rates. We will promptly notify you of any claim subject to this Section, but our failure to promptly notify you will only affect your obligations to the extent that our failure prejudices your ability to defend the claim. You may: (a) use counsel of your own choosing (subject to our written consent) to defend against any claim; and (b) settle the claim as you deem appropriate, provided that you obtain our prior written consent before entering into any settlement.</p>

<p>11. MISCELLANEOUS</p>
<p>(a) General. We and you are independent contractors, and neither party, nor any of their respective affiliates, is an agent of the other for any purpose or has the authority to bind the other. This Agreement does not create any third party beneficiary rights in any individual or entity that is not a party to this Agreement. You will not assign this Agreement, or delegate or sublicense any of your rights under this Agreement, without our prior written consent. Our failure to enforce any provision of this Agreement will not constitute a present or future waiver of such provision nor limit our right to enforce such provision at a later time. If any portion of this Agreement is held to be invalid or unenforceable, the remaining portions of this Agreement will remain in full force and effect.</p>

<p>(b) Entire Agreement. This Agreement is the entire agreement between you and us regarding the subject matter of this Agreement. This Agreement supersedes all prior or contemporaneous representations, understandings, agreements, or communications between you and us, whether written or verbal, regarding the subject matter of this Agreement.</p>

<p>(c) Notice. All communications and notices to be made or given pursuant to this Agreement must be in English. We may provide any notice to you under this Agreement by posting a notice on the Service site or sending a message to the email address associated with your account. You will be deemed to have received any email sent to the email address then associated with your account when we send the email, whether or not you actually receive the email. To give us notice under this Agreement, you must email us at support@getwriteflow.com.</p>

<p>(d) Choice of Law; Consent to Jurisdiction. The laws of British Columbia govern this Agreement and any dispute of any sort that might arise between you and us without reference to any applicable conflict of laws rules. You consent to exclusive jurisdiction and venue of British Columbia courts. We may seek injunctive or other relief in any state, federal, or national court of competent jurisdiction for any actual or alleged infringement of our, our affiliates, or any third party’s intellectual property or other proprietary rights. The United Nations Convention for the International Sale of Goods does not apply to this Agreement.</p>

<p>(e) Force Majeure. We are not liable for any delay or failure to perform any obligation under this Agreement where the delay or failure results from any cause beyond our reasonable control, including acts of God, labor disputes or other industrial disturbances, systemic electrical, telecommunications, or other utility failures, earthquake, storms or other elements of nature, blockages, embargoes, riots, acts or orders of government, acts of terrorism, or war.</p>

<p>(f) Amendments. We may amend this Agreement at any time by posting a revised version on the Service site or by otherwise notifying you by email. The amended Terms of Service become effective upon posting on the Service site or as stated in our email notice message. By continuing to use the Services after the effective date of any amendment to this Agreement, you agree to be bound by the amended Terms of Service. Please check the site for the applicable Service regularly.</p>



        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
  p {
    margin-bottom: 1.5rem;
  }
</style>
